version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - .env
    ports: 
      - ${PORT}:${PORT}
    depends_on: 
      - db
    volumes:
      - ./:/app
    networks: 
      - some-network
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks: 
      - some-network
        
networks: 
  some-network:
    name: some-network
    driver: bridge