version: '3.8'

services:
  app:
    container_name: app
    build: 
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file: 
      - .env
    ports: 
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/db?schema=public
    depends_on: 
      - db
    volumes:
      - ./:/app
    networks: 
      - some-network
  db:
    container_name: db
    build:
      dockerfile: Dockerfile
      context: ./docker
    restart: always
    env_file: 
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks: 
      - some-network
        
networks: 
  some-network:
    name: some-network
    driver: bridge