# FROM node:alpine3.17

# WORKDIR /app

# COPY package*.json ./

# # RUN npm install
# RUN npm ci && npm cache clean --force

# COPY . .

# EXPOSE ${PORT}

# CMD [ "npm", "run", "start:prisma" ]
FROM node:alpine3.17 as build

WORKDIR /app

COPY package*.json .

RUN npm ci && npm cache clean --force

COPY . .

FROM node:alpine3.17

COPY --from=build /app /app

WORKDIR /app

EXPOSE ${PORT}

CMD [ "npm", "run", "start:prisma" ]
