version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - ./:/app
      - node:/app/node_modules
    networks:
      - docker-network
  database:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/log/postgresql/postgresql.log
    networks:
      - docker-network

volumes:
  node:
  data:
  logs:

networks:
  docker-network:
    driver: bridge
